# Generated by Django 3.0.3 on 2020-02-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Post created on')),
            ],
        ),
    ]
